spring.application.name=tododb

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/tododb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.jackson.parser.allow-trailing-comma=true

server.port=${PORT:${SERVER_PORT:8084}}

# JWT
jwt.secret=${JWT_SECRET}
jwt.access-token.expiration=${JWT_ACCESS_EXPIRATION:3600000}
jwt.refresh-token.expiration=${JWT_REFRESH_EXPIRATION:604800000}


# CORS
cors.allowed-origins=${ALLOWED_ORIGINS:http://localhost:4200,http://localhost:8081,https://kanbanapp-1-4mob.onrender.com}
cors.allowed-methods=GET,POST,PUT,DELETE,PATCH,OPTIONS
cors.allowed-headers=*
cors.allow-credentials=true
cors.max-age=3600

# Swagger
springdoc.swagger-ui.enabled=${SWAGGER_ENABLED:false}
springdoc.api-docs.enabled=${SWAGGER_ENABLED:false}
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.url=/v3/api-docs
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.tryItOutEnabled=true
springdoc.swagger-ui.filter=true
springdoc.swagger-ui.syntaxHighlight.theme=monokai
springdoc.swagger-ui.displayRequestDuration=true
springdoc.swagger-ui.supportedSubmitMethods=get,put,post,delete,options,head,patch
springdoc.packages-to-scan=com.kanban.kanbanapp.controller